5주차 | 홈페이지 api 연결, 선물 추가 페이지 데이터 연결
EFUB-GeumJaSsi/GiftU-Front pull request #103
Opened 2024-08-03 17:29 UTC by rwaeng

## ✅ PR 체크 리스트

- [x] PR 제목: n주차 | 작업사항 요약
- [x] Reviewers, Assignees, Labels, Milestone, Development 설정

## ✨ 작업사항
캘린더.js 두 번째 훅 작성, 홈페이지 api 연결, 선물 추가 페이지 데이터 연결

## 📸 구현 상태
홈페이지 api 연결

https://github.com/user-attachments/assets/4ab22d4e-c548-4d13-af57-d4ca2c505d61

선물 추가 페이지 연결

https://github.com/user-attachments/assets/c9e66b27-b079-45d2-ab5a-bdf4682b8774

## 💡 리뷰 요청사항

- 리뷰 담당자에게 전하고 싶은 말

2024-08-05 15:23 UTC, hyerinxx requested changes
5주차 수고하셨습니다❤

2024-08-05 15:23 UTC, hyerinxx commented on src/components/common/BottomBackgroundComponent.jsx
> +  z-index: 999;
z-index는 왜 추가하는 건가요? `position: fixed;`로 하면 기존 페이지 흐름에서 벗어나서 화면에 고정되어서 z-index 추가하지 않아도 될 것 같아요!

2024-08-05 15:23 UTC, hyerinxx commented on src/components/common/PasswordComponent.jsx
>            {/* ButtonComponent 사용하기 */}
PasswordComponent 개발 담당자분께 말씀드리려고 했는데 발빠르게 수정해주셨군요 ㅋㅋ 주석은 지워주셔도 돼요
```suggestion
```

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/FundingInfo/FundingInfoPage.jsx
펀딩 개설 취소 후에 뒤로가기 못하도록 다음과 같이 수정해주세요!
```jsx
      navigate('/my/funding/open', { replace: true });
```

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/FundingJoin/CompletePage.jsx
> +      onClick={window.location.replace('/')}
navigate로 통일해주세요!
```suggestion
      onClick={() => navigate('/', { replace: true })}
```

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/FundingJoin/CompletePage.jsx
```jsx
import { useNavigate } from 'react-router-dom';
```

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/FundingJoin/CompletePage.jsx
>  const CompletePage = () => {
```suggestion
const CompletePage = () => {
  const navigate = useNavigate();
```

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/FundingOpen/GiftAddPage.jsx
> +  const { giftData, imageData } = useContext(DataContext);
어떻게 `setGiftData` 안 쓰고 구현하셨는지 코드가 이해가 잘 안되어서 내일 회의에서 여쭤볼게요

2024-08-05 15:23 UTC, hyerinxx commented on src/pages/Home/HomePage.jsx
앗 이 부분은 제가 하는 거였는데 전달이 잘 안 되었나봐요

2024-08-05 15:23 UTC, hyerinxx commented
펀딩 참여 IndexPage 관련 내용은 아직 개발 중일까요?

2024-08-05 15:33 UTC, rwaeng commented
결제 api 부분을 오늘 전달받아서 늦어도 수요일까지는 작업완료 하겠습니다!

2024-08-06 02:13 UTC, rwaeng commented on src/components/FundingInfo/PriceProgressBar.jsx
props 수를 줄여서 전달하라는 얘기일까요? 
props 전달 없이 바로 변수를 사용한다는 말이 이해가 안 되는데 조금 더 설명해 줄 수 있을까요??

2024-08-06 03:04 UTC, rwaeng commented on src/components/common/BottomBackgroundComponent.jsx
> +  z-index: 999;
금액바에서 금액 동그라미에 클릭 시 z-index를 부여했더니 여기 z-index보다 높아서 동그라미만 위로 올라오더라고요!

2024-08-06 03:07 UTC, rwaeng commented on src/pages/FundingOpen/GiftAddPage.jsx
> +  const { giftData, imageData } = useContext(DataContext);
요거 splice 사용해서 원본 배열이 변경되도록 했어요

2024-08-06 03:09 UTC, rwaeng commented on src/pages/Home/HomePage.jsx
개발 일정에 적혀있어서 했는데 소통 오류가 있었나 봐요 
제 부분 삭제해도 되는데 다시 커밋할까요!? 아님 머지하면서 해결하는 게 편하신가요

2024-08-06 07:37 UTC, hyerinxx commented on src/pages/FundingOpen/GiftAddPage.jsx
> +  const { giftData, imageData } = useContext(DataContext);
state는 setter 통해서만 값을 변경할 수 있는 줄 알았는데 원본 배열을 수정하는 게 가능했군요…

2024-08-06 07:39 UTC, hyerinxx commented on src/pages/Home/HomePage.jsx
다시 커밋해주시면 더 편할 거 같아요 감사합니다😄

2024-08-06 09:54 UTC, hyerinxx approved these changes
일단 머지 확인 완

2024-08-06 09:54 UTC, merged

2024-08-07 17:47 UTC, hyerinxx commented on src/components/FundingInfo/PriceProgressBar.jsx
대면 회의로 전달했습니다 ㅋㅋ