💄ui: 공통 컴포넌트 | 태그 구분 컴포넌트
EFUB-GeumJaSsi/GiftU-Front pull request #15
Opened 2024-07-06 14:12 UTC by sj0919

## ✅ PR 체크 리스트

- [ ] PR 제목: n주차 | 작업사항 요약
- [ ] Reviewers 설정
- [ ] Assignees 설정
- [ ] Labels 설정

## ✨ 작업사항

알림창과 펀딩 목록페이지 위에 쓰는 공통 컴포넌트입니다.
펀딩 목록페이지의 경우 '전체/친구/펀딩' -> '전체/진행/종료' 로 글자만 바꿔서 사용하면 될것 같습니다.
클릭시 해당 버튼의 색깔을  #67c5d2로 설정하였고 클릭하지 않은 경우 #d6d9de로 색깔이 표시됩니다.

## 📸 구현 상태
![image](https://github.com/EFUB-GeumJaSsi/GiftU-Front/assets/161692586/d272eae5-2b34-4788-a34f-aa269448e81c)

## 💡 리뷰 요청사항

- 리뷰 담당자에게 전하고 싶은 말
- 저렇게만 구현하면 되는지 정확히 모르겠어서 혹시 더 필요한 부분 있으면 보고 말씀해주시면 수정해서 반영하도록 하겠습니다!

2024-07-07 14:14 UTC, hyerinxx requested changes

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +  height: 31px;
텍스트는 width와 height를 지정할 필요가 없습니다.
```suggestion
```

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +  font-color: black;
`font-color` 속성은 존재하지 않습니다. `color` 속성입니다.
또, 디자인에 따라 `var(--black)` 사용하시면 됩니다.
```suggestion
  color: var(--black);
```

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +  padding-top: 43px;
상단 여백은 개별 요소에 종속되기보다는, 페이지 전체 레이아웃을 조정할 때 함께 설정하는 것이 좋습니다. 관련 있는 설정끼리 함께 두었을 때 코드 리팩토링이 수월합니다. 
```suggestion
```

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +const BodyContainer = styled.div`
```suggestion
const BodyContainer = styled.div`
  padding-top: 43px;
```

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationItem.jsx
친구 추가 알림에서 친구의 닉네임이 길 때, 펀딩 관련 알림에서 펀딩 이름이 길 때 문자열을 처리하는 부분이 누락되었습니다. Figma에서 알림 섹션의 마지막 프레임을 참고하여 추가해주세요.

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +const HeaderWord = styled.div`
시맨틱 태그 활용하면 더욱 좋겠습니다~
```suggestion
const HeaderWord = styled.header`
```

2024-07-07 14:14 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
> +const ContentContainer = styled.div`
```suggestion
const ContentContainer = styled.main`
```

2024-07-09 00:14 UTC, sj0919 commented
넵 반영해서 수정하도록 하겠습니다!

2024-07-09 08:09 UTC, hyerinxx approved these changes
수정 확인했습니다

2024-07-09 08:09 UTC, merged