3주차 | 축하메세지 수정 페이지, 선물후기 작성 페이지, 튜토리얼 페이지 퍼블리싱, 2주차 수정사항 반영
EFUB-GeumJaSsi/GiftU-Front pull request #54
Opened 2024-07-20 14:19 UTC by sj0919

## ✅ PR 체크 리스트

- [ ] PR 제목: n주차 | 작업사항 요약
- [ ] Reviewers 설정
- [ ] Assignees 설정
- [ ] Labels 설정

## ✨ 작업사항

1. 축하메세지 수정 페이지 퍼블리싱
2. 선물후기 작성 페이지 퍼블리싱
3. 튜토리얼 페이지 퍼블리싱
4. 2주차 수정사항 반영
   1)알림페이지 관련 수정
      - 친구 추가 알림 클릭 시, 수락/거절 모달창 나타남 
      - 펀딩 관련 알림 클릭 시, 펀딩 상세 페이지로 이동
   2) 필요한 페이지마다 BottomBackground 컴포넌트 적용  => 아령언니 컴포넌트 수정사항 있다해서 추후 추가수정 필요
   3) SearchPage.jsx에 Tag 컴포넌트 반영
   
 3주차에 완성할것
   - 알림페이지 관련 수정: 알림 메시지 목록 시간역순 정렬 =>API 연결하면서 같이 할게요!
   - 캘린더 수정: 찬희랑 같은거라 다음주에 찬희 PR 보고 수정해놓을게요!

## 📸 구현 상태
1. 축하메세지 수정 페이지 퍼블리싱
https://github.com/user-attachments/assets/43167e9b-0da8-4b28-a0a7-a6d14508cde4

2. 선물후기 작성 페이지 퍼블리싱
https://github.com/user-attachments/assets/fd352776-9f7d-485e-9216-1facefe4cdec

3. 튜토리얼 페이지 퍼블리싱
![image](https://github.com/user-attachments/assets/f0398737-3087-4212-8d9e-e0b732270401)

4. 2주차 수정사항 반영
   1)알림페이지 관련 수정
      - 친구 추가 알림 클릭 시, 수락/거절 모달창 나타남 
      - 펀딩 관련 알림 클릭 시, 펀딩 상세 페이지로 이동
https://github.com/user-attachments/assets/71d98622-2c36-453b-ace0-c8476e630118

## 💡 리뷰 요청사항

- 리뷰 담당자에게 전하고 싶은 말

2024-07-21 15:30 UTC, hyerinxx requested changes
3주차 수고하셨어요❤
1주차에 비해서 코드가 훨씬 깔끔해졌네요👍
이번주 코드 수정도 파이팅입니다!

2024-07-21 15:30 UTC, hyerinxx commented on src/pages/Notification/NotificationPage.jsx
>          />
이 부분 라우팅하는 것보다는 전체/친구/펀딩 선택을 저장할 state를 하나 만들고, 태그 구분 컴포넌트를 라디오 버튼으로 하고, 버튼 선택에 따라 onClick으로 state 값 바꿔서 전체/친구/펀딩 조건부 렌더링하면 어떨까요? 알림 페이지에서 라우팅으로 필터링하는 경우는 거의 못 본 것 같아요.

2024-07-21 15:30 UTC, hyerinxx commented on src/pages/ProfileEdit/ProfileEditPage.jsx
> +        <SImageContainer>
이 부분도 앞의 코드 리뷰 참고해서 수정해주세요!

2024-07-22 02:01 UTC, sj0919 commented on src/assets/common/logo.svg
7개 svg파일 모두 Tutorial 폴더 만들어서 이동시켰습니다!

2024-07-22 02:09 UTC, sj0919 commented on src/components/Notification/NotificationItemComponent.jsx
수정완료했고 컴포넌트 사용하는 NotificationPage에서도 경로 수정 완료했습니다!

2024-07-22 03:15 UTC, sj0919 commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +              금액 <span style={{ color: 'var(--orange-pri)' }}>*</span>
SStarWrapper로 수정했습니다!

2024-07-22 03:25 UTC, sj0919 commented on src/pages/Tutorial/TutorialPage.jsx
> +    <SLayout>
<>로 수정했습니다!

2024-07-22 06:05 UTC, sj0919 commented on src/pages/Tutorial/TutorialPage.jsx
> +          <SSubContentContainer>
컴포넌트 이용해서 반복되는 코드 수정했고 네이밍도 수정했습니다!
component/Tutorial에 TitleDescription.jsx로 만들어서 넣어놓았습니다!

2024-07-22 06:45 UTC, sj0919 commented on src/pages/ProfileEdit/ProfileEditPage.jsx
> +        <SImageContainer>
수정 완료했습니다!

2024-07-23 02:48 UTC, hyerinxx approved these changes
4주차에 추가 수정 부탁드립니다!

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +        </SBigForm>
설문지 구성처럼, `<form>` 요소는 전체 인풋필드를 감싸 하나의 폼을 형성합니다. 개별 인풋필드를 그룹핑하는 요소는 `<fieldset>` 입니다! 아래는 스타일링을 고려하지 않은 예시입니다.

```js
<form>
  <fieldset>
    <legend>금액</legend>
    <input type='text' />
  </fieldset>
  <fieldset>
    <legend>이름</legend>
    <input type='text' />
  </fieldset>
  <fieldset>
    <legend>축하메시지</legend>
    <textarea></textarea>
  </fieldset>
</form>
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +`;
단순히 요소 간 간격을 띄우기 위해 스타일링하는 거라면 `width`, `height`를 지정하지 않습니다! 불필요합니다.
```suggestion
const SSmallForm = styled.form`
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 8px;
`;
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +`;
코드 내용이 동일할 경우 하나만 선언하여 여러 곳에 활용하면 좋겠죠?
```suggestion
const SBigForm = styled.form`
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 8px;
`;
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +`;
텍스트 스타일링에 불필요한 코드가 있어요!

```suggestion
const SLegend = styled.legend`
  color: var(--black);
  font-size: 16px;
  font-weight: 500;
`;
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +`;
그거 아시나요? styled-components로 이미 선언된 태그를 또다시 활용하여 스타일을 덧입힐 수 있습니다. 아래와 같이 작성할 경우 많은 코드를 줄일 수 있습니다! 단, 이 경우에 `SLegend`는 `SRequiredLegend`보다 윗줄에서 먼저 선언되어야 합니다.
```suggestion
const SRequiredLegend = styled(SLegend)`
  &::after {
    content: '*';
    color: var(--orange-pri);
  }
`;
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +  }
불필요한 코드가 있어요!

```suggestion
  &:focus {
    border: 2px solid var(--orange-pri);
  }
```

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/MyOpenFunding/MessageEditPage.jsx
> +        </SBigForm>
축하메시지와 같이 여러 줄의 문자열을 입력하는 경우에는 `textarea` 태그가 적절하지만, 금액이나 이름과 같이 입력이 길지 않은 경우에는 일반적으로 `input` 태그를 활용합니다.

2024-07-23 02:48 UTC, hyerinxx commented on src/components/Tutorial/TitleDescription.jsx
> +    </>
`SContentboxContainer`로 가장 바깥을 감싸고 있으니 빈 태그로 한번더 감싸지 않아도 될 것 같아요~

```suggestion
    <SContentboxContainer>
      <STitleBoxContainer>
        <SNumWrapper color={color}>{num}</SNumWrapper>
        <STitleWrapper>{title}</STitleWrapper>
      </STitleBoxContainer>
      <SExplainBoxWrapper>
        <SExplainWrapper>{description}</SExplainWrapper>
      </SExplainBoxWrapper>
      {Component && <Component />}
    </SContentboxContainer>
```

2024-07-23 02:48 UTC, hyerinxx commented on src/components/Tutorial/TitleDescription.jsx
> +`;
1. styled-components 컨벤션을 지켜주세요.
2. 용도에 맞는 적절한 태그를 사용해주세요.
3. 텍스트 스타일링을 하는 경우, 레이아웃을 조정하는 경우 등을 고려하여 꼭 필요한 코드만 작성해주세요.
4. 1~3주차의 PR을 한번더 읽어주세요!

2024-07-23 02:48 UTC, hyerinxx commented on src/pages/ProfileEdit/ProfileEditPage.jsx
앞의 코드리뷰 참고하여 HTML 태그 구조를 중점으로 수정해주세요!

2024-07-23 02:50 UTC, merged