4주차 | 오류 수정, 프로필이미지 추가, 셀프 클로징
EFUB-GeumJaSsi/GiftU-Front pull request #70
Opened 2024-07-23 15:57 UTC by sj0919

## ✅ PR 체크 리스트

- [ ] PR 제목: n주차 | 작업사항 요약
- [ ] Reviewers 설정
- [ ] Assignees 설정
- [ ] Labels 설정

## ✨ 작업사항

1. 오류 수정 --> commit 이슈로 오류났던것들 수정 및 복구
2. 프로필 이미지 추가 --> 프로필 편집 페이지와 알림페이지에 프로필이미지 추가
3. 지금까지 작업한 부분에 대한 셀프 클로징
4. 지난주 BackgroundBottom 컴포넌트 수정에 따라 해당 컴포넌트 사용하는 부분 코드 수정

## 📸 구현 상태
프로필 편집 페이지에 프로필이미지 추가한 화면
![image](https://github.com/user-attachments/assets/f35c0055-13c1-4e8e-b5b2-bbba37af10cb)

알림페이지에 프로필이미지 추가한 화면
![image](https://github.com/user-attachments/assets/998c2ff9-b8c1-4374-8144-a90182e38fb8)

## 💡 리뷰 요청사항

- 리뷰 담당자에게 전하고 싶은 말

2024-07-24 14:47 UTC, rwaeng requested changes

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/MessageEditPage.jsx
> +  ></ButtonComponent>
```suggestion
  <ButtonComponent
    btnInfo={{
      text: '수정하기',
      width: '335px',
      color: 'orange',
    }}
  />
```
셀프클로징으로!

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/MessageEditPage.jsx
> +        <FundingPercentage color='orange'></FundingPercentage>
```suggestion
        <FundingPercentage color='orange' />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/MessageEditPage.jsx
> +          <SInput type='text' value={tempList[0].name} readonly></SInput>
```suggestion
          <SInput type='text' value={tempList[0].name} readonly />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/MessageEditPage.jsx
> +          ></SBigTextarea>
```suggestion
          <SBigTextarea
            onChange={handleInputChange}
            value={MsgText}
          />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/ReviewEditPage.jsx
> +    ></ButtonComponent>
```suggestion
    <ButtonComponent
      btnInfo={{
        text: '완료',
        width: '335px',
        color: reviewText ? 'jade' : 'gray',
      }}
    />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/ReviewEditPage.jsx
> +      <BackHeaderComponent text='선물후기'></BackHeaderComponent>
```suggestion
      <BackHeaderComponent text='선물후기' />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Edit/ReviewEditPage.jsx
> +          ></STextarea>
```suggestion
          <STextarea
            placeholder='선물 후기를 작성해주세요!'
            value={reviewText}
            onChange={handleInputChange}
          />
```

2024-07-24 14:47 UTC, rwaeng commented on src/pages/Notification/NotificationPage.jsx
> +        <SProfileWrapper src={image} />
이 부분도 프로필 default 이미지 설정하면 좋을 거 같아요~

2024-07-24 14:47 UTC, rwaeng commented on src/pages/ProfileEdit/ProfileEditPage.jsx
>  const SForm = styled.form`
캘린더 위치가 깨져서
`position: relative;` 추가하고 
SCalendarWrapper에서 left랑 bottom으로 조정 필요할 거 같아요
![image](https://github.com/user-attachments/assets/1182bea7-f426-455e-9bcd-110e06afcc9f)

2024-07-26 07:30 UTC, sj0919 commented on src/pages/ProfileEdit/ProfileEditPage.jsx
>  const SForm = styled.form`
수정했습니다!

2024-07-26 07:58 UTC, sj0919 commented on src/pages/Notification/NotificationPage.jsx
> +        <SProfileWrapper src={image} />
이부분을 radio 방식으로 바꾸고있어서 그거 수정완료하고 커밋하면서 이것도 반영해놓겠습니다!

2024-07-26 14:32 UTC, rwaeng commented
radio로 바꾸고 수정완료 하면 확인하고 pr 닫을게요~!!

2024-07-26 14:33 UTC, rwaeng approved these changes
radio로 바꾸고 수정완료 하면 확인하고 머지할게요~!!

2024-07-27 08:55 UTC, rwaeng approved these changes
라디오 버튼 짱👍👍

2024-07-27 08:55 UTC, rwaeng commented on src/pages/Notification/NotificationPage.jsx
> +        <SProfileWrapper src={image} alt='profile' />
여기도 default 이미지 추가해주세요~~

2024-07-28 11:53 UTC, merged

2024-07-29 12:24 UTC, sj0919 commented on src/pages/Notification/NotificationPage.jsx
> +        <SProfileWrapper src={image} alt='profile' />
완료했습니다!